trigger:
  branches:
    include:
      - main
      # - ft/pipeline

pr:
  branches:
    include:
      - main
      # - ft/pipeline

pool:
  vmImage: 'windows-latest'

variables:
  MAVEN_CACHE_FOLDER: $(USERPROFILE)\.m2\repository

steps:
  - checkout: self
    clean: true

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
      path: $(MAVEN_CACHE_FOLDER)
    displayName: Cache Maven Dependencies

  - script: mvn clean test
    displayName: Build Maven Project

  # Archive target folder
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'target'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true
    displayName: Archive Build Output

  # Publish Artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: Publish Artifact
